[format]
quote-style = "double"

[lint]
fixable = ["ALL"]
select = [
  "A",
  "AIR",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C",
  "C4",
  "COM",
  "D",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FBT",
  "FLY",
  "FIX",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "N",
  "NPY",
  "PIE",
  "PGH",
  "PD",
  "PL",
  "PLE",
  "PLR",
  "PLW",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RSE",
  "RET",
  "RUF",
  "S",
  "SLF",
  "SIM",
  "TCH",
  "TD",
  "TID",
  "T10",
  "TRY",
  "W",
  "UP",
]
ignore = [
  "ANN101",
  "B008",
  "C901",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D203",
  "D205",
  "D213",
  "D401",
  "D406",
  "D407",
  "D417",
  "E401",
  "E501",
  "ERA001",
  "F403",
  "F405",
  "F541",
  "FA102",
  "PIE807",
  "PLC0415",
  "PLR0913",
  "N815",
  "RUF100",
  "UP037",
]

[lint.isort]
case-sensitive = true
combine-as-imports = true
force-sort-within-sections = false
force-wrap-aliases = true
order-by-type = true

[lint.pydocstyle]
convention = "google"
